server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  config:
    import: optional:configserver:http://localhost:8888 #Ruta del config-server

eureka:
  instance:
    hostname: localhost #host del servidor
  client:
    register-with-eureka: false #decirle a Eureka que no se registre a si mismo
    fetch-registry: false
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/ #configurando ruta del servidor eureka