server:
  #port: 8761
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    #hostname: eureka #host del servidor docker
    #hostname: localhost #host del servidor
    hostname: ${HOSTNAME}
  client:
    register-with-eureka: false #decirle a Eureka que no se registre a si mismo
    fetch-registry: false
    server-url:
     # defaultZone: http://eureka:${server.port}/eureka/ #configurando ruta del servidor eureka docker
      #defaultZone: http://localhost:${server.port}/eureka/ #configurando ruta del servidor eureka
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
