server:
  port: 8090

spring:
  application:
    name: msvc-flight-prediction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/flight_prediction
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000