eureka:
  client:
    # IMPORTANTE: Debe ser true para encontrar a los otros servicios
    register-with-eureka: true
    fetch-registry: true
    service-url:
      # Apuntar al contenedor de Eureka, no a localhost
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: prediccion
          uri: lb://msvc-flight-prediction
          predicates:
            - Path=/prediccion/**

        - id: api-routes
          uri: lb://msvc-flight-prediction
          predicates:
            - Path=/api/**

        - id: FlightStats
          uri: lb://msvc-flight-prediction
          predicates:
            - Path=/vuelos/stats/**

        - id: auth
          uri: lb://msvc-flight-prediction
          predicates:
            - Path=/login/**,/usuarios/**

        - id: spring-doc
          uri: lb://msvc-flight-prediction
          predicates:
            - Path=/v3/api-docs/**, /swagger-ui/**, /swagger-ui.html